# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import barrier_pb2 as barrier__pb2


class BarrierStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.wait = channel.unary_unary(
                '/barrier.Barrier/wait',
                request_serializer=barrier__pb2.BarrierRequest.SerializeToString,
                response_deserializer=barrier__pb2.BarrierResponse.FromString,
                )


class BarrierServicer(object):
    """Missing associated documentation comment in .proto file."""

    def wait(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BarrierServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'wait': grpc.unary_unary_rpc_method_handler(
                    servicer.wait,
                    request_deserializer=barrier__pb2.BarrierRequest.FromString,
                    response_serializer=barrier__pb2.BarrierResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'barrier.Barrier', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Barrier(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def wait(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/barrier.Barrier/wait',
            barrier__pb2.BarrierRequest.SerializeToString,
            barrier__pb2.BarrierResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
